### ISSUE TITLE
Bills missing attributes when loaded via Subscription associations

### ISSUE THREAD

**Issue by savef** [gocardless/gocardless-ruby#81]
When loading a `Bill` via `Subscription#bills` they are missing attributes for `Bill#can_be_cancelled`, `#can_be_retried` and `#charge_customer_at`, values which are there if you load the bill directly.

Here are some steps to hopefully recreate the issue:
```
> sub = GoCardless::Subscription.find("SUB001")
> b1 = sub.bills.first
> b2 = GoCardless::Bill.find(b1.id)

> [b1.id, b1.status, b1.can_be_cancelled, b1.can_be_retried, b1.charge_customer_at]
=> ["BIL001", "pending", nil, nil, nil]
> [b2.id, b2.status, b2.can_be_cancelled, b2.can_be_retried, b2.charge_customer_at]
=> ["BIL001", "pending", true, false, Thu, 09 Jul 2015 00:00:00 +0000]
```

All the other attributes (id, amount, amount_minus_fees, gocardless_fees, partner_fees, currency, name, status, description, created_at, merchant_id, user_id, paid_at, source_type, source_id, uri, payout_id, is_setup_fee) seem to be fine, and are in sync.

**Comment by greysteil** [comment]
Good point. Looks like this is specific to the API itself, rather than this gem, though.

I have a feeling `can_be_retried` and `can_be_cancelled` are expensive to calculate so aren't included on index views, but there's no reason not to include `charge_customer_at`. I'll see if we can change that for `charge_customer_at` and document it for the others.

**Comment by savef** [comment]
Cool. As well as documenting it for the others calling the function should raise an exception I think, so it's clear to the developer they cannot get that value on that object (and so they don't assume the nil is essentially a false). Also it might be nice for `Bill` to provide a `reload` or `load_full` method which fetches all its attributes.

**Comment by greysteil** [comment]
Just deployed an update to the API - `charge_customer_at` should be there. @jacobpgn - can you take a look at updating the docs on this?

@savef - you're right about erroring being a better interface, but we probably won't change this gem. We're encouraging all integrators to use the GoCardless Pro API from now on, which is a lot cleaner - https://developer.gocardless.com/pro/2015-07-06/#overview. In the next couple of months we'll put the original API into long-term maintenance mode.

**Comment by savef** [comment]
> `charge_customer_at` should be there

It is, thanks.

> We're encouraging all integrators to use the GoCardless Pro API from now on

Does this mean you will be encouraging all users to pay for the [£200 per month](https://gocardless.com/pricing/) subscription? Or is *GoCardless Pro* a separate thing from the *GoCardless Pro API*? (And to be clear, can we use the Pro API and continue to only pay the 1%?)

**Comment by isaacseymour** [comment]
You can use the Pro API paying 1% with no monthly overhead. We sort-of mention this at the top of the Basic API docs:
> Would you like to beta test our new API? We're working on a new system - based on our Pro API - for developers that don't need all of the Pro features but still want to build powerful integrations with GoCardless. If you're interested in beta testing it with us, just email help@gocardless.com.

... but this could definitely be much much clearer in the Pro API docs! I'll add a tweaked version of that note to them.

Thanks for pointing this out!

**Comment by savef** [comment]
Thanks!
